---

language: node_js
dist: trusty
sudo: false
node_js:
  - "6"
  - "7"
  - "8"

before_script:
  - ./node_modules/.bin/ganache-cli -a 8 --gasPrice 200 -l 100000000 -e 100 > /dev/null &
  - ./node_modules/.bin/ethereum-bridge > /dev/null &
  - sleep 5

script:
  - ./node_modules/.bin/truffle compile &&
    ./node_modules/.bin/truffle test

notifications:
  email:
    on_success: change
    on_failure: always
