---

language: node_js
dist: trusty
sudo: false
node_js:
  - "6"
  - "7"
  - "8"


install:
  - npm install --only=dev

script:
  - make build  

notifications:
  email:
    on_success: change
    on_failure: always
