---

language: node_js
dist: trusty
sudo: required
git:
  submodules: false

services:
  - docker
node_js:
  - "6"
  - "7"
  - "8"

before_script:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - make build
  - make start  
  - sleep 60

script:
  - docker-compose -v
  - docker -v
  - docker-compose logs
  - make test

notifications:
  email:
    on_success: change
    on_failure: always
