version: "2.2"

services:
  ganache:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile

    command: ./ganache-cli -a 8 --gasPrice 200 -l 100000000 -e 100  --rpc --rpccorsdomain="*" --rpcaddr="ganache" --rpcport="8545" -h 0.0.0.0
    ports:
      - 8545:8545

  bridge:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    command: /bin/bash -c "cd /node_modules/ethereum-bridge && node bridge -H ganache:8545 --dev"
    restart: always
    depends_on:
      - ganache
